### ISSUE TITLE
Not working on windows 10 too ! Installed successfully, but doesnt show anything ! No errors No output nothing

### ISSUE THREAD

**Issue by ashwinkhode** [TTtie/discord.nvim#1]

**Comment by TTtie** [comment]
Hello :wave:
Sorry for the long wait. Is your issue with the plugin resolved? If not, please describe further what is the problem - the title is not descriptive enough for me to get what is up with the plugin.

Thanks!

**Comment by ashwinkhode** [comment]
Sorry, my bad. So I am getting this error

Error: local discord client not found
![Screenshot (49)](https://user-images.githubusercontent.com/53361996/116619483-20f6d780-a95e-11eb-8349-5e18254a6ef4.png)

When I try to run `:DiscordUpdatePresence`, I get no message whatsoever.
Please let me know what else you need, I will gladly help you :)

## Environment
OS: Windows 10 ( Not using WSL btw )
Terminal: Alacritty (xterm-256color)
Vim: NeoVim 0.5.0
checkhealth: 
![Screenshot 2021-04-30 024922](https://user-images.githubusercontent.com/53361996/116619906-babe8480-a95e-11eb-805a-a61ac2e8fdf9.png)

**Comment by TTtie** [comment]
@ashwinkhode Are you sure Discord (the desktop app, it won't work in a browser) is running? If it is and it's still not working, I'll try and take a spin on my Windows install tomorrow, as it's already late here. If you run into any other issues, please let me know!

**Comment by ashwinkhode** [comment]
Yeah, I am running Discord (the desktop app) & it's still not working I tried using nvim-qt also but no success :(
Hey don't worry about it! Take your time. It's just I think there are not many Discord RPC plugins for neovim that works out of the box. It would be nice to have atleast one but a good working plugin. 
Please try and let me know if I can help in any way :)
Thank you :)

**Comment by TTtie** [comment]
Hm... it works on my side on commit at the latest commit (`344f6908d5e15b7338cb2df86707bad9efb71e40`).
If you open the developer console and look for 
```
[RPCServer:IPC] Starting on \\?\pipe\discord-ipc-X
```

Is the number where X is other than 0? If not, it is not handled by neither the upstream nor this plugin (but it might be a nice enhancement!)

**Comment by ashwinkhode** [comment]
I cant find any message like that. This is the error I am getting
![Screenshot 2021-04-30 163638](https://user-images.githubusercontent.com/53361996/116687082-402f4c80-a9d2-11eb-84e5-fb4fb86edb41.png)

I installed ws locally and globally but still getting that error. What is going wrong here?

**Comment by TTtie** [comment]
Uh-oh! This is something you shouldn't be getting... you might want to give reinstalling Discord a shot at this point.

**Comment by ashwinkhode** [comment]
Yo thanks man! It's working :)
There was some problem with my discord. Appreciate your time and effort <3

![Screenshot 2021-04-30 191818](https://user-images.githubusercontent.com/53361996/116704259-d53d4000-a9e8-11eb-937e-31e0ecc64dec.png)


I was just thinking, is it possible to add support for neovim running in WSL? 🤔

**Comment by TTtie** [comment]
Re neovim in WSL - it might be possible if you have a translation layer from UDS to Windows named pipes
